### ISSUE TITLE
ziggurat-foundations 0.7.0

### ISSUE THREAD

**Issue by peletiah** [ergo/testscaffold#3]
```Could not find a version that satisfies the requirement ziggurat-foundations>=0.7.0 (from -r requirements.txt (line 3))```

0.7.0 not in pypi yet, would 0.6.8 also work?

**Comment by ergo** [comment]
Nope, you need to use trunk 0.7 - i have yet to release it when I'm confident every thing is good there.
I might release it tommorow if I find the time.

**Comment by peletiah** [comment]
okey dokey

**Comment by ergo** [comment]
fixed
